### ISSUE TITLE
OneDrive, Google Drive, DropBox, Box.com, Box.net

### ISSUE THREAD

**Issue by dj4oC** [junaid33/opensource.builders#506]
ownCloud Infinite Scale is the Open Source On-Premis alternative to the closed source products mentioned in the title.

**Comment by jcklpe** [comment]
@dj4oC  Apologies, but this is in an invalid post format. We require the title be the closed source software with the open source alternatives in comments. Please clarify what this software is an open source alternative to. If adjustments are not made in the next 30 days, the post will be wiped from our repo. Thank you.

**Comment by dj4oC** [comment]
> @dj4oC Apologies, but this is in an invalid post format. We require the title be the closed source software with the open source alternatives in comments. Please clarify what this software is an open source alternative to. If adjustments are not made in the next 30 days, the post will be wiped from our repo. Thank you.

Hi @jcklpe I do apologies for the wrong post. I hope this version matches the required format.

**Comment by jcklpe** [comment]
@dj4oC  Oh dope right owncloud, I wasn't even thinking. We do actually have a ticket for that already: https://github.com/junaid33/opensource.builders/issues/67

I'm going to close this ticket and add some of the things you added to the title of the other ticket so that it's more encompassing. Feel free to write up whatever info you'd like about Owncloud on that ticket as a comment. I'm a long time Nextcloud user, so I'm less familar with Owncloud but any additional information you add is more than welcome!

**Comment by dj4oC** [comment]
Nexcloud is a fork of the "old" LAMP stack by ownCloud.
ownCloud decided to start a more modern approach some years ago and rewrote the entire Platform at Go Microservices. 
I'll try to write some more words at #67

**Comment by jcklpe** [comment]
Awesome! I remember hearing about that. Sounded really cool.
